name: CI-sim-ci
on:
  issue_comment:
    types: [created]
jobs:
  pre-merge-ci:
    if: github.event.issue.pull_request && github.event.comment.body == "action run-ci"
    runs-on: ubuntu-20.04
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Run CI
        run: echo ${{ github.event.comment.body }}
