name: CI-sim-ci

on:
  issue_comment:
    types: [created]

jobs:
  pre-merge-ci:
    if: ${{ github.event.issue.pull_request && github.event.comment.body == 'action run-ci' }}
    runs-on: ubuntu-20.04
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      # Need this first step to init the git repo.
      - name: Check out code
        uses: actions/checkout@v2
      - name: Checkout pull request
        id: pull_request
        run: |
          echo ::set-output name=head_ref::$(gh pr view ${{ github.event.issue.number }} --json headRefName --template 'refs/heads/{{.headRefName}}')
          git fetch origin +refs/pull/${{ github.event.issue.number }}/merge
          git checkout FETCH_HEAD
      - name: Run CI
        run: |
          echo Triggered by comment ${{ github.event.comment.body }}
      - name: Update status check
        env:
          SUCCESS: ${{ success() }}
        run: |
          git fetch origin ${{ steps.pull_request.outputs.head_ref }}
          if [ $SUCCESS = true ]
          then
            gh api --method POST -H 'Accept: application/vnd.github.v3+json'                                \
              /repos/${{ github.repository }}/statuses/$(git rev-parse FETCH_HEAD)                          \
              -f state='success'                                                                            \
              -f target_url='https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}' \
              -f context 'CI-sim-ci/pre-merge-ci'                                                           \
              -f description='Successful'
          else
            gh api --method POST -H 'Accept: application/vnd.github.v3+json'                                \
              /repos/${{ github.repository }}/statuses/$(git rev-parse FETCH_HEAD)                          \
              -f state='failure'                                                                            \
              -f target_url='https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}' \
              -f context 'CI-sim-ci/pre-merge-ci'                                                           \
              -f description='Failed'
          fi
