name: CI-sim-ci
on:
  issue_comment:
    types: [created]
jobs:
  pre-merge-ci:
    if: github.event.issue.pull_request && github.event.comment.body == 'action run-ci'
    runs-on: ubuntu-20.04
    steps:
      # Need this first step to init the git repo.
      - name: Check out code
        uses: actions/checkout@v2
      - name: Checkout pull request
        run: |
          git fetch origin +refs/pull/${{ github.event.issue.number }}/merge
          git checkout FETCH_HEAD
      - name: Run CI
        run: echo ${{ github.event.comment.body }}
      - name: Update status check
        if: ${{ success() }}
        run: |
          gh api \
            --method POST \
            -H "Accept: application/vnd.github.v3+json" \
            /repos/${{ github.repository }}/statuses/$(git rev-parse HEAD) \
            -f state='success'
           -f target_url='https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}'
           -f description='Successful'
      - name: Update status check
        if: ${{ failure() }}
        run: |
          gh api \
            --method POST \
            -H "Accept: application/vnd.github.v3+json" \
            /repos/${{ github.repository }}/statuses/$(git rev-parse HEAD) \
            -f state='failure'
           -f target_url='https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}'
           -f description='Failed'
