name: CI-version-check-for-master
on:
  pull_request:
    types: [opened, synchronize, edited, reopened]
    branches: ['master']
jobs:
  version-check-for-master:
    if: github.base_ref == 'master'
    runs-on: ubuntu-20.04
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Match version string
        run: |
          echo Match regex "v[0-9]+\.[0-9]+\.[0-9]+" before merging to ${{ github.base_ref }}
          grep -E '^constexpr char kSoftwareVersion\[\] = "v[0-9]+\.[0-9]+\.[0-9]+-dev";$' version.txt || exit 1
