name: CI-version-check
on: [pull_request]
jobs:
  version-check-targeting-master:
    if: github.base_ref == 'master'
    runs-on: ubuntu-20.04
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Ensure ${{ github.base_ref }} version string match regex "v[0-9]+\.[0-9]+\.[0-9]+-dev"
        run: grep -E '^constexpr char kSoftwareVersion\[\] = "v[0-9]+\.[0-9]+\.[0-9]+-dev";$' version.txt || exit 1
  version-check-targeting-release:
    if: startsWith(github.base_ref, 'release-')
    runs-on: ubuntu-20.04
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Ensure ${{ github.base_ref }} version string match regex "v[0-9]+\.[0-9]+\.[0-9]+"
        run: grep -E '^constexpr char kSoftwareVersion\[\] = "v[0-9]+\.[0-9]+\.[0-9]+";$' version.txt || exit 1
