name: CI-version-check
on:
  pull_request:
    branches:
      - 'master'
      - 'release-**'
jobs:
  version-check-targeting-master:
    if: github.base_ref == 'master'
    runs-on: ubuntu-20.04
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Match version string with regex "v[0-9]+\.[0-9]+\.[0-9]+-dev" before merging to ${{ github.base_ref }}
        run: grep -E '^constexpr char kSoftwareVersion\[\] = "v[0-9]+\.[0-9]+\.[0-9]+-dev";$' version.txt || exit 1
  version-check-targeting-release:
    if: startsWith(github.base_ref, 'release-')
    runs-on: ubuntu-20.04
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Match version string with regex "v[0-9]+\.[0-9]+\.[0-9]+" before merging to ${{ github.base_ref }}
        run: grep -E '^constexpr char kSoftwareVersion\[\] = "v[0-9]+\.[0-9]+\.[0-9]+";$' version.txt || exit 1
